version: '3'
services:
  backend:
    image: cycleapp2:latest
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/backend
      #- frontend_build:/frontend/dist

    command: 'tail -f /dev/null'
    env_file:
      - envs/dev.env
    depends_on:
      - database
  database:
    image: postgres:16
    ports:
      - '5432:5432'
    env_file:
      - envs/dev.env

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  #frontend_build: do we need it ?