version: '3'
services:
  backend:
    image: modifythis
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
      #- frontend_build:/frontend/dist de we need it?

    command: 'tail -f /dev/null'
    env_file:
      - envs/dev.env
    depends_on:
      - database
  database:
    image: postgres:16
    ports:
      - 5555:5432
    env_file:
      - envs/dev.env

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  #frontend_build: do we need it ?