version: '3.6'

services:
  backend:
    image: modifythis
    command: 'sh /scripts/prod.sh'
    env_file:
      - ./envs/prod.env
    depends_on:
      - database
    volumes:
      - static_files:/static-files
      - media_files:/media-files
      - frontend_build:/frontend/dist

  database:
    image: postgres:16
    env_file:
      - ./envs/prod.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_files:/static-files
      - media_files:/media-files
      - ./nginx:/etc/nginx/conf.d/
      - frontend_build:/frontend_build
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  postgres_data:
  static_files:
  media_files:
  frontend_build:
