name: django_cycable_app
dependencies:
  - python=3.12.2
  - pip=23.3.1
  - psycopg2=2.9.9
  - pip:
    - django==5.0.3
    - djangorestframework==3.15.0
    - djangorestframework-simplejwt==5.3.1
    - pillow==10.2.0
    - drf_yasg==1.21.7
    - rest_framework_simplejwt==0.0.2
    - flake8==7.0.0
    - gunicorn==21.2.0
    - django-cors-headers==4.3.1
    - qrcode==7.4.2
