# Generated by Django 5.0.3 on 2024-04-17 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
        ('incidentReport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='incident_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidentReport.incidentreport'),
        ),
    ]
