# Generated by Django 5.0.3 on 2024-04-17 08:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('geolocation_camera', models.CharField(blank=True, max_length=100)),
                ('use_current_time', models.BooleanField(default=False)),
                ('custom_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('object_id', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='BicycleAccident',
            fields=[
                ('incident_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='incidentReport.incidentreport')),
                ('involved_parties', models.CharField(choices=[('Car', 'Car'), ('Bus, trolleybus, tram', 'Bus, trolleybus, tram'), ('Commercial vehicle', 'Commercial vehicle'), ('Motorcycle', 'Motorcycle'), ('Another bicycle', 'Another bicycle'), ('Pedestrian', 'Pedestrian'), ('E-Scooter', 'E-Scooter'), ('Road markings or infrastructure', 'Road markings or infrastructure'), ('Other', 'Other')], max_length=100)),
                ('was_police_called', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BicycleTheft',
            fields=[
                ('incident_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='incidentReport.incidentreport')),
                ('was_bicycle_locked', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NearMiss',
            fields=[
                ('incident_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='incidentReport.incidentreport')),
                ('involved_parties', models.CharField(choices=[('Car', 'Car'), ('Bus, trolleybus, tram', 'Bus, trolleybus, tram'), ('Commercial vehicle', 'Commercial vehicle'), ('Motorcycle', 'Motorcycle'), ('Another bicycle', 'Another bicycle'), ('Pedestrian', 'Pedestrian'), ('E-Scooter', 'E-Scooter'), ('Road markings or infrastructure', 'Road markings or infrastructure'), ('Other', 'Other')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Violations',
            fields=[
                ('incident_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='incidentReport.incidentreport')),
                ('change_to_add', models.CharField(max_length=400)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
