# Generated by Django 5.0.3 on 2024-04-17 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('incidentReport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='bicycletheft',
            name='incident_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bicycle_theft', to='incidentReport.incidentreport'),
        ),
        migrations.AddField(
            model_name='bicycleaccident',
            name='incident_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bicycle_accident', to='incidentReport.incidentreport'),
        ),
        migrations.AddField(
            model_name='nearmiss',
            name='incident_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='near_miss', to='incidentReport.incidentreport'),
        ),
        migrations.AddField(
            model_name='violations',
            name='incident_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='incidentReport.incidentreport'),
        ),
    ]
