# Generated by Django 5.0.3 on 2024-04-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidentReport', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='object_id',
        ),
    ]
